---
game: !ruby/hash:Sinatra::IndifferentHash
  name: City of Lies - Development
  category: Fantasy
  description: The Development instance of City of Lies
  website: ''
  public_game: false
  game_status: In Development
