---
l5r:
  starting_experience_points: 40
  wounds_per_rank_multiplier: 2
  include_kata: true
  include_kiho: true
  include_maho: false
  starting_glory: 1.0
  starting_status: 1.0
  max_ability_rank: 4
  xp_cron:
    day_of_week:
    - Mon
    hour:
    - 20
    minute:
    - 25
  periodic_xp: 2
  shortcuts:
    families: family
    schools: school
    traits: trait
    skills: skill
    advs: adv
    disadvs: disadv
    technique: tech
    techniques: tech
    techs: tech
    spells: spell
    clans: clan
    health: wounds
    wound: wounds
    wound/rem: wounds/heal
    wounds/rem: wounds/heal
    health/rem: wounds/heal
