---
l5r:
  spells:
    -
      name: Sense
      ring: All
      mastery: 1
      pg: Core pg. 164
    -
      name: Summon
      ring: All
      mastery: 1
      pg: Core pg. 165
    -
      name: Commune
      ring: All
      mastery: 1
      pg: Core pg. 165
    -
      name: Blessed Wind
      ring: Air
      mastery: 1
      pg: Core pg. 167
    -
      name: Benten's Touch
      ring: Air
      mastery: 2
      pg: Core pg. 167
