l5r:
  techniques:
      -
        name: The Way of the Crab
        school: Hida Bushi
        rank: 1
        pg: Core pg. 106
      -
        name: The Mountain Does Not Move
        school: Hida Bushi
        rank: 2
        pg: Core pg. 106
      -
        name: Two Pincers, One Mind
        school: Hida Bushi
        rank: 3
        pg: Core pg. 106
      -
        name: Devastating Blow
        school: Hida Bushi
        rank: 4
        pg: Core pg. 106
      -
        name: The Mountain Does Not Fall
        school: Hida Bushi
        rank: 5
        pg: Core pg. 107
