---
l5r:
  schools:
        -
          name: Hida Bushi
          clan: Crab
          trait_bonus: Stamina
          skills: [Athletics, Defense, Heavy Weapons/Tetsubo, Intimidation, Kenjutsu, "Lore: Shadowlands"]
          skill_choice: "Any:Bugei"
          shugenja: false
          honor: 3.5
          starting_technique: The Way of the Crab
          techniques: ['"The Way of the Crab"', '"The Mountain Does Not Move"', '"Two Pincers, One Mind"', '"Devastating Blow"', '"The Mountain Does Not Fall"']
        -
          name: Kuni Shugenja
          clan: Crab
          trait_bonus: Willpower
          skills: [Calligraphy/Cipher, Defense, "Lore: Shadowlands", "Lore: Shadowlands", "Lore: Theology", Spellcraft]
          skill_choice: "Any:Weapon"
          shugenja: true
          affinity: Earth
          deficiency: Air
          spells: Universal, 3 Earth, 3 Fire, and 1 Water
          spell_choice: "3 Earth, 2 Fire, 1 Water"
          honor: 2.5
          starting_technique: Gaze into Shadow
        -
          name: Yasuki Courtier
          clan: Crab
          trait_bonus: Perception
          skills: [Commerce/Appraisal, Courtier, Defense, Etiquette, Intimidation, Sincerity/Deceit]
          skill_choice: "Any:Merchant"
          shugenja: false
          honor: 2.5
          starting_technique: The Way of the Carp
          techniques: ['"The Way of the Carp"', '"Do As We Say"', '"Treasures of the Carp"', '"Wiles of the Carp"', '"What is Yours is Mine"']
        -
          name: Hiruma Bushi
          clan: Crab
          trait_bonus: Willpower
          skills: [Athletics, Hunting, Kenjutsu/Katana, Kyujutsu, "Lore: Shadowlands", Stealth]
          skill_choice: "Any:Skill"
          shugenja: false
          honor: 4.5
          starting_technique: "Torch's Flame Flickers"
          techniques: ["'Torch's Flame Flickers'", "'Wolf's Little Lesson'", '"Hummingbird Wings"', '"Shark Smells Blood"', '"Daylight Wastes No Movement"']
        -
          name: Kakita Bushi
          clan: Crane
          trait_bonus: Reflexes
          skills: [Etiquette, Iaijutsu/Focus, Kenjutsu, Kyujutsu, Sincerity, Tea Ceremony]
          skill_choice: "Any:Bugei or High"
          honor: 6.5
          starting_technique: The Way of the Crane
          techniques: ['"The Way of the Crane"', '"Speed of Lightning"', '"First and Last Strike"', '"One Strike, Two Cuts"', '"Strike With No Thoughts"']
