---
l5r:
  traits:
    -
      name: Reflexes
      ring: Air
      description: "Represents a character's ability to instantly react to events around him."
    -
      name: Awareness
      ring: Air
      description: "Represents a character's intuition and general ability to empathize with others."
    -
      name: Willpower
      ring: Earth
      description: "Determines a character's ability to focus on the task before him and resist manipulation."
    -
      name: Stamina
      ring: Earth
      description: "Determines a character's ability to endure constant physical activity and recover from wounds."
    -
      name: Intelligence
      ring: Fire
      description: "Measures a character's ability to gain new knowledge and put it to use."
    -
      name: Agility
      ring: Fire
      description: "Represents a character's hand-eye coordination and general physical athleticism."
    -
      name: Perception
      ring: Water
      description: "Represents a character's attention to events unfolding around him."
    -
      name: Strength
      ring: Water
      description: "Represents a character's pure physical power."
