---
l5r:
  advantages:
    -
      name: Absolute Direction
      subtype: Mental
      cost: '1'
      restriction: None
      pg: Core pg. 146
    -
      name: Allies
      subtype: Social
      cost: Varies
      restriction: descriptor
      pg: Core pg. 146
    -
      name: Balance
      subtype: Mental
      cost: '2'
      restriction: None
      pg: Core pg. 146
    -
      name: Blackmail
      subtype: Social
      cost: Varies
      restriction: descriptor
      pg: Core pg. 146
    -
      name: Bland
      subtype: Physical
      cost: '2'
      restriction: None
      pg: Core pg. 146
    -
      name: Blissful Betrothal
      subtype: Social
      cost: '3'
      restriction: None
      pg: Core pg. 146
    -
      name: Blood of Osano-Wo
      subtype: Spiritual
      cost: '4'
      restriction: None
      pg: Core pg. 147
    -
      name: Chosen by the Oracles
      subtype: Spritual
      cost: '6'
      restriction: None
      pg: Core pg. 147
    -
      name: Clear Thinker
      subtype: Mental
      cost: '3'
      restriction: None
      pg: Core pg. 147
    -
      name: Crab Hands
      subtype: Physical
      cost: '3'
      restriction: None
      pg: Core pg. 147
    -
      name: Craft
      subtype: Mental
      cost: '3'
      restriction: None
      pg: Core pg. 147
    -
      name: Dangerous Beauty
      subtype: Physical
      cost: '3'
      restriction: None
      pg: Core pg. 147
    -
      name: Daredevil
      subtype: Mental
      cost: '3'
      restriction: None
      pg: Core pg. 147
    -
      name: Dark Paragon
      subtype: Mental
      cost: '5'
      restriction: Yes
      pg: Core pg. 147
    -
      name: Darling of the Court
      subtype: Social
      cost: '2'
      restriction: descriptor
      pg: Core pg. 148
    -
      name: Different School
      subtype: Social
      cost: '5'
      restriction: Yes
      pg: Core pg. 148
    -
      name: Elemental Blessing
      subtype: Spiritual
      cost: '4'
      restriction: None
      pg: Core pg. 148
    -
      name: Enlightened
      subtype: Spiritual
      cost: '6'
      restriction: Yes
      pg: Core pg. 148
    -
      name: Fame
      subtype: Social
      cost: '3'
      restriction: Yes
      pg: Core pg. 148
    -
      name: Forbidden Knowledge
      subtype: Mental
      cost: '5'
      restriction: [descriptor, note]
      pg: Core pg. 148
    -
      name: Friendly Kami
      subtype: Spiritual
      cost: '5'
      restriction: None
      pg: Core pg. 149
    -
      name: Friend of the Brotherhood
      subtype: Spirtual
      cost: '5'
      restriction: None
      pg: Core pg. 149
    -
      name: Friend of the Elements
      subtype: Spritual
      cost: '4'
      restriction: None
      pg: Core pg. 149
    -
      name: Gaijin Gear
      subtype: Material
      cost: '5'
      restriction: [descriptor, note]
      pg: Core pg. 149
    -
      name: Great Destiny
      subtype: Spiritual
      cost: '5'
      restriction: None
      pg: Core pg. 150
    -
      name: Great Potential
      subtype: Varies
      cost: '5'
      restriction: None
      pg: Core pg. 150
    -
      name: Hands of Stone
      subtype: Physical
      cost: '6'
      restriction: None
      pg: Core pg. 150
    -
      name: Heart of Vengeance
      subtype: Social
      cost: '5'
      restriction: None
      pg: Core pg. 150
    -
      name: Hero of the People
      subtype: Social
      cost: '2'
      restriction: Yes
      pg: Core pg. 150
    -
      name: Imperial Spouse
      subtype: Social
      cost: '5'
      restriction: note
      pg: Core pg. 150
    -
      name: Inari's Blessing
      subtype: Spritual
      cost: '3'
      restriction: None
      pg: Core pg. 150
    -
      name: Inheritance
      subtype: Material
      cost: '5'
      restriction: [descriptor, note]
      pg: Core pg. 150
    -
      name: Inner Gift
      subtype: Spiritual
      cost: '7'
      restriction: descriptor
      pg: Core pg. 151
    -
      name: Irreproachable
      subtype: Mental
      cost: '2'
      restriction: None
      pg: Core pg. 151
    -
      name: Ishiken-Do
      subtype: Spiritual
      cost: '8'
      restriction: Yes
      pg: Core pg. 151
    -
      name: Kharmic Tie
      subtype: Spiritual
      cost: '1-5'
      restriction: descriptor
      ranked: true
      max_rank: 5
      pg: Core pg. 151
    -
      name: Languages
      subtype: Mental
      cost: '1 or 3'
      restriction: descriptor
      ranked: true
      max_rank: 2
      pg: Core pg. 151
    -
      name: Large
      subtype: Physical
      cost: '4'
      restriction: None
      pg: Core pg. 151
    -
      name: Leadership
      subtype: Social
      cost: '6'
      restriction: None
      pg: Core pg. 151
    -
      name: Luck
      subtype: Spiritual
      cost: '3/6/9'
      restriction: None
      ranked: true
      max_rank: 3
      pg: Core pg. 151
    -
      name: Magic Resistance
      subtype: Spiritual
      cost: '2/4/6'
      restriction: None
      ranked: true
      max_rank: 3
      pg: Core pg. 151
    -
      name: Multiple Schools
      subtype: Social
      cost: '10'
      restriction: Yes
      pg: Core pg. 151
    -
      name: Paragon
      subtype: Mental
      cost: '7'
      restriction: note
      pg: Core pg. 152
    -
      name: Perceived Honor
      subtype: Social
      cost: '2/rank'
      max_rank: 3
      restriction: None
      ranked: true
      pg: Core pg. 152
    -
      name: Precise Memory
      subtype: Mental
      cost: '3'
      restriction: None
      pg: Core pg. 152
    -
      name: Prodigy
      subtype: Physical
      cost: '12'
      restriction: None
      pg: Core pg. 152
    -
      name: Quick
      subtype: Physical
      cost: '6'
      restriction: None
      pg: Core pg. 152
    -
      name: Quick Healer
      subtype: Physical
      cost: '3'
      restriction: None
      pg: Core pg. 152
    -
      name: Read Lips
      subtype: Mental
      cost: '4'
      restriction: None
      pg: Core pg. 152
    -
      name: Sacred Weapon
      subtype: Material
      cost: Varies
      restriction: note
      pg: Core pg. 152
    -
      name: Sage
      subtype: Mental
      cost: '4'
      restriction: None
      pg: Core pg. 153
    -
      name: Sensation
      subtype: Social
      cost: '3'
      restriction: None
      pg: Core pg. 153
    -
      name: Servant
      subtype: Material
      cost: '5'
      restriction: descriptor
      pg: Core pg. 153
    -
      name: Seven Fortunes' Blessing
      subtype: Spiritual
      cost: '4'
      restriction: descriptor
      pg: Core pg. 153
    -
      name: Silent
      subtype: Physical
      cost: '3'
      restriction: None
      pg: Core pg. 154
    -
      name: Soul of Artistry
      subtype: Mental
      cost: '4'
      restriction: None
      pg: Core pg. 154
    -
      name: Strength of the Earth
      subtype: Physical
      cost: '3'
      restriction: None
      pg: Core pg. 154
    -
      name: Tactician
      subtype: Mental
      cost: '4'
      restriction: None
      pg: Core pg. 154
    -
      name: "Tattoo: Balance"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tatooed Order
      pg: Core pg. 114
    -
      name: "Tatoo: Bamboo"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Blaze"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Centipede"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Crab"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Crane"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Dragon"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Hawk"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Ki-Rin"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Lion"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Mantis"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Mountain"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Ocean"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 114
    -
      name: "Tattoo: Phoenix"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 115
    -
      name: "Tattoo: Scorpion"
      subtype: Physical        
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 115
    -
      name: "Tattoo: Spider"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 115
    -
      name: "Tattoo: Storm"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 115
    -
      name: "Tattoo: Void"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 115
    -
      name: "Tattoo: Wind"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 115
    -
      name: "Tattoo: Wolf"
      subtype: Physical
      cost: 'None'
      restriction: Togashi Tattooed Order
      pg: Core pg. 115
    -
      name: Touch of the Spirit Realms
      subtype: Spiritual
      cost: '5'
      restriction: None
      pg: Core pg. 154
    -
      name: Virtuous
      subtype: Mental
      cost: '3'
      restriction: None
      pg: Core pg. 155
    -
      name: Voice
      subtype: Physical
      cost: '3'
      restriction: None
      pg: Core pg. 155
    -
      name: Wary
      subtype: Mental
      cost: '3'
      restriction: None
      pg: Core pg. 155
    -
      name: Way of the Land
      subtype: Mental
      cost: '2'
      restriction: None
      pg: Core pg. 155
    -
      name: Wealthy
      subtype: Material
      cost: '1/rank'
      ranked: true
      max_rank: 3
      restriction: None
      pg: Core pg. 155
