---
l5r:
  schools:
        -
          name: Hida Bushi
          clan: Crab
          trait_bonus: Stamina
          skills: [Athletics, Defense, Heavy Weapons/Tetsubo, Intimidation, Kenjutsu, "Lore: Shadowlands"]
          skills_display: "Athletics, Defense, Heavy Weapons/Tetsubo, Intimidation, Kenjutsu, Lore: Shadowlands, and Any Bugei skill"
          skill_choice: "Any Bugei skill"
          shugenja: false
          honor: 3.5
          starting_technique: The Way of the Crab
          techniques: ['"The Way of the Crab"', '"The Mountain Does Not Move"', '"Two Pincers, One Mind"', '"Devastating Blow"', '"The Mountain Does Not Fall"']
          pg: Core pg. 106
        -
          name: Kuni Shugenja
          clan: Crab
          trait_bonus: Willpower
          skills: [Calligraphy/Cipher, Defense, "Lore: Shadowlands", "Lore: Shadowlands", "Lore: Theology", Spellcraft]
          skills_display: "Calligraphy/Cipher, Defense, Lore: Shadowlands, Lore: Theology, Spellcraft, and Any Weapon skill"
          skill_choice: "Any Weapon skill"
          shugenja: true
          affinity: Earth
          deficiency: Air
          spells: Universal, 3 Earth, 3 Fire, and 1 Water
          spell_choice: "3 Earth, 2 Fire, 1 Water"
          honor: 2.5
          starting_technique: Gaze into Shadow
          pg: Core pg. 107
        -
          name: Yasuki Courtier
          clan: Crab
          trait_bonus: Perception
          skills: [Commerce/Appraisal, Courtier, Defense, Etiquette, Intimidation, Sincerity/Deceit]
          skills_display: "Commerce/Appraisal, Courtier, Defense, Etiquette, Intimidation, Sincerity/Deceit, and Any Merchant skill"
          skill_choice: "Any Merchant skill"
          shugenja: false
          honor: 2.5
          starting_technique: The Way of the Carp
          techniques: ['"The Way of the Carp"', '"Do As We Say"', '"Treasures of the Carp"', '"Wiles of the Carp"', '"What is Yours is Mine"']
          pg: Core pg. 107
        -
          name: Hiruma Bushi
          clan: Crab
          trait_bonus: Willpower
          skills: [Athletics, Hunting, Kenjutsu/Katana, Kyujutsu, "Lore: Shadowlands", Stealth]
          skills_display: "Athletics, Hunting, Kenjutsu/Katana, Kyujutsu, Lore: Shadowlands, Stealth, and Any skill"
          skill_choice: "Any skill"
          shugenja: false
          honor: 4.5
          starting_technique: "Torch's Flame Flickers"
          techniques: ["'Torch's Flame Flickers'", "'Wolf's Little Lesson'", '"Hummingbird Wings"', '"Shark Smells Blood"', '"Daylight Wastes No Movement"']
          pg: Core pg. 108
        -
          name: Kakita Bushi
          clan: Crane
          trait_bonus: Reflexes
          skills: [Etiquette, Iaijutsu/Focus, Kenjutsu, Kyujutsu, Sincerity, Tea Ceremony]
          skills_display: "Etiquette, Iaijutsu/Focus, Kenjutsu, Kyujutsu, Sincerity, Tea Ceremony, and Any Bugei or High skill"
          skill_choice: "Any Bugei or High skill"
          shugenja: false
          honor: 6.5
          starting_technique: The Way of the Crane
          techniques: ['"The Way of the Crane"', '"Speed of Lightning"', '"First and Last Strike"', '"One Strike, Two Cuts"', '"Strike With No Thoughts"']
          pg: Core pg. 109
        -
          name: Asahina Shugenja
          clan: Crane
          trait_bonus: Awareness
          skills: [Calligraphy/Cipher, Etiquette, "Lore: Theology", Meditation, Spellcraft]
          skills_display: "Calligraphy/Cipher, Etiquette, 'Lore: Theology', Meditation, Spellcraft, Any Artisan Skill, and Any High Skill"
          skill_choice: "Any Artisan and Any High skill"
          shugenja: true
          affinity: Air
          deficiency: Fire
          spells: Universal, 3 Air, 2 Water, 1 Earth
          spell_choice: 3 Air, 2 Water, 1 Earth
          honor: 6.5
          starting_technique: "The Soul's Grace"
          pg: Core pg. 110
        -
          name: Doji Courtier
          clan: Crane
          trait_bonus: Awareness
          skills: [Calligraphy, Courtier/Manipulation, Etiquette/Courtesy, "Perform: Storytelling", Sincerity, Tea Ceremony]
          skills_display: "Calligraphy, Courtier/Manipulation, Etiquette/Courtesy, 'Perform: Storytelling', Sincerity, Tea Ceremony, and Any Artisan or Perform Skill"
          skill_choice: "Any Artisan or Perform skill"
          shugenja: false
          honor: 6.5
          starting_technique: The Soul of Honor
          techniques: ['"The Soul of Honor"', '"Speaking in Silence"', '"The Perfect Gift"', '"Voice of Honor"', '"The Gift of the Lady"']
          pg: Core pg. 110
        -
          name: Daidoji Iron Warriors
          clan: Crane
          trait_bonus: Agility
          skills: [Battle, Defense, Defense, Iaijutsu, Kenjutsu/Katana, Kyujutsu]
          skills_display: "Battle, Defense 2, Iaijutsu, Kenjutsu/Katana, Kyujutsu, and Any one Skill"
          skill_choice: "Any one skill"
          shugenja: false
          honor: 6.5
          starting_technique: The Force of Honor
          techniques: ['"The Force of Honor"', '"The Shield of Faith"', '"Strike Beneath the Veil"', '"Vigilance of Mind"', '"To Tread on the Sword"']
          pg: Core pg. 111
        -
          name: Mirumoto Bushi
          clan: Dragon
          trait_bonus: Stamina
          skills: [Defense, Iaijutsu, Kenjutsu/Katana, "Lore: Shugenja", Meditation, "Lore: Theology"]
          skills_display: "Defense, Iaijutsu, Kenjutsu/Katana, 'Lore: Shugenja', 'Lore: Theology', Meditation, and Any one Bugei or High Skill"
          skill_choice: "Any one Bugei or High skill"
          shugenja: false
          honor: 4.5
          starting_technique: Way of the Dragon
          techniques: ['"Way of the Dragon"', '"The Calm in Midst of Thunder"', '"Strong and Swift"', '"Furious Retaliation"', '"Heart of the Dragon"']
          pg: Core pg. 113
        -
          name: Tamori Shugenja
          clan: Dragon
          trait_bonus: Stamina
          skills: [Athletics, Calligraphy/Cipher, Defense, Divination, "Lore: Theology", Medicine, Spellcraft]
          skills_display: "Athletics, Calligraphy/Cipher, Defense, Divination, 'Lore: Theology', Medicine, Spellcraft"
          skill_choice: None
          shugenja: true
          affinity: Earth
          deficiency: Air
          spells: Universal, 3 Earth, 2 Fire, 1 Water
          spell_choice: 3 Earth, 2 Fire, 1 Water
          honor: 4.5
          starting_technique: Flesh of the Elements
          pg: Core pg. 113
        -
          name: Kitsuki Investigator
          clan: Dragon
          trait_bonus: Perception
          skills: [Courtier, Etiquette/Courtesy, Investigation/Interrogation, Kenjutsu, Meditation, Sincerity]
          skills_display: "Courtier, Etiquette/Courtesy, Investigation/Interrogation, Kenjutsu, Meditation, Sincerity, and Any Lore skill"
          skill_choice: "Any one Lore skill"
          shugenja: false
          honor: 5.5
          starting_technique: "Kitsuki's Method"
          techniques: ["'Kitsuki's Method'", '"Wisdom the Wind Brings"', '"Know the Rhythm of the Heart"', '"Finding the Path"', '"The Eyes Betray the Heart"']
          pg: Core pg. 114
        -
          name: Togashi Tattooed Order
          clan: Dragon
          trait_bonus: Void
          skills: [Athletics, Defense, "Craft: Tattooing", Jiujutsu, Meditation]
          skills_display: "Athletics, Defense, 'Craft: Tattooing', Jiujutsu, Meditation, Any one Lore skill, and Any one non-Low skill"
          skill_choice: "Any one Lore and any one non-Low skill"
          shugenja: false
          honor: 4.5
          starting_technique: Blood of the Kami
          techniques: ['"Blood of the Kami"', '"Body of Stone"', '"Blessing of the Kami"', '"Will of Stone"', '"Touch of the Kami"']
          pg: Core pg. 114
        -
          name: Akodo Bushi
          clan: Lion
          trait_bonus: Perception
          skills: [Battle/Mass Combat, Defense, Kenjutsu, Kyujutsu, "Lore: History", Sincerity]
          skills_display: "Battle/Mass Combat, Defense, Kenjutsu, Kyujutsu, 'Lore: History', Sincerity, and Any one Bugei or High Skill"
          skill_choice: "Any one Bugei or High skill"
          shugenja: false
          honor: 6.5
          starting_technique: The Way of the Lion
          techniques: ['"The Way of the Lion"', '"Strength of Purity"', '"Strength of My Ancestors"', '"Triumph Before Battle"', "'Akodo's Final Lesson'"]
          pg: Core pg. 116
        -
          name: Kitsu Shugenja
          clan: Lion
          trait_bonus: Perception
          skills: [Battle, Calligraphy/Cipher, Etiquette, "Lore: History", "Lore: Theology", Spellcraft]
          skills_display: "Battle, Calligraphy/Cipher, Etiquette, 'Lore: History', 'Lore: Theology', Spellcraft, and Any one High or Bugei Skill"
          skill_choice: Any one High or Bugei skill
          shugenja: true
          affinity: Water
          deficiency: Fire
          spells: Universal, 3 Water, 2 Air, 1 Earth
          spell_choice: 3 Water, 2 Air, 1 Earth
          honor: 6.5
          starting_technique: Eyes of the Ancestors
          pg: Core pg. 117
        -
          name: Ikoma Bard
          clan: Lion
          trait_bonus: Intelligence
          skills: [Courtier, Etiquette, "Lore: History/Lion Clan", "Perform: Storytelling", Sincerity/Honesty]
          skills_display: "Courtier, Etiquette, 'Lore: History/Lion Clan', 'Perform: Storytelling', Sincerity/Honesty, Any one High Skill, and Any one Bugei Skill"
          skill_choice: Any one High and Any one Bugei skill
          shugenja: false
          honor: 6.5
          starting_technique: The Herald of Glory
          techniques: ['"The Herald of Glory"', '"The Heart of the Lion"', '"The Voice of the Ancestors"', '"The Strength of Tradition"', '"Every Lion is Your Brother"']
          pg: Core pg. 118
        -
          name: Matsu Berserker
          clan: Lion
          trait_bonus: Strength
          skills: [Battle, Jiujutsu, Kenjutsu/Katana, Kyujutsu, "Lore: History"]
          skills_display: "Battle, Jiujutsu, Kenjutsu/Katana, Kyujutsu, 'Lore: History', and Any 2 Bugei Skills"
          skill_choice: "Any 2 Bugei skills"
          shugenja: false
          honor: 6.5
          starting_technique: "The Lion's Roar"
          techniques: ["'The Lion's Roar'", "'Matsu's Fury'", "'The Lion's Charge'", "'Matsu's Courage'", "'The Lion's Victory'"]
          pg: Core pg. 119
        -
          name: Disciples of Sun Tao
          clan: None
          trait_bonus: Reflexes
          skills: [Athletics, Defense, Hunting, Iaijutsu, Kenjutsu]
          skills_display: "Athletics, Defense, Hunting, Iaijutsu, Kenjutsu, Any 2 skills"
          skill_choice: "Any 2 skills"
          shugenja: false
          honor: 4.5
          starting_technique: The Gaze of Sun Tao
          pg: Core pg. 234
        -
          name: Self-Taught Shugenja
          clan: None
          trait_bonus: Willpower
          skills: [Athletics, Hunting, Meditation, Spellcraft]
          skills_display: "Athletics, Hunting, Meditation, Spellcraft, and Any 3 non-High skills"
          skill_choice: "Any 3 non-High skills"
          shugenja: true
          affinity: Any non-Void
          deficiency: Opposing Element and 1 Choice
          aff_def_choice: true
          spells: Universal and any five you can cast. None can be for an element you have a deficiency in.
          spell_choice: Any 5 non-Deficiency
          honor: 4.0
          starting_technique: "The Kami's Gift"
          pg: EotE pg. 205
        -
          name: Dutiful Disciple Shugenja
          clan: None
          trait_bonus: Intelligence
          skills: [Calligraphy, "Lore: Theology", Meditation, Spellcraft]
          skills_display: 'Calligraphy, "Lore: Theology", Meditation, Spellcraft, Any 2 skills, and Any Lore skill'
          skill_choice: "Any 2 skills and Any Lore skill"
          shugenja: true
          affinity: "Any non-Void"
          deficiency: "Opposing Element"
          aff_def_choice: true
          spells: Universal, 3 Affinity, 2 non-Deficiency, and 1 different non-Deficiency.
          spell_choice: 3 Affinity, 2 non-Deficiency, 1 different non-Deficiency
          honor: 4.0
          starting_technique: Soul of Study
          pg: EotE pg. 205
        -
          name: Ronin Order Shugenja
          clan: None
          trait_bonus: Awareness
          skills: [Calligraphy/Cipher, Divination, "Lore: Theology", Meditation, Spellcraft]
          skills_display: 'Calligraphy/Cipher, Divination, "Lore: Theology", Meditation, Spellcraft, Any skill, and Any Lore skill'
          skill_choice: "Any skill and Any Lore skill"
          shugenja: true
          affinity: "Air"
          deficiency: "Earth"
          spells: Universal, 3 Air, 2 Water, and 1 Fire
          spell_choice: 3 Air, 2 Water, 1 Fire
          honor: 5.0
          starting_technique: The Path of Discipline
          pg: EotE pg. 205
        -
          name: Four Temples
          clan: Monk
          trait_bonus: Awareness
          skills: [Courtier, Etiquette, Jiujutsu, "Lore: Theology/Shintao", Meditation]
          skills_display: 'Courter, Etiquette, Jiujutsu, "Lore: Theology/Shintao", Meditation, Any 2 skills'
          skill_choice: "Any 2 skills"
          shugenja: false
          honor: 6.5
          starting_technique: Soul of Civility
          pg: Core pg. 231
        -
          name: The Order of Heroes
          clan: Monk
          trait_bonus: Perception
          skills: [Athletics, Defense, Jiujutsu, "Lore: Theology", Meditation]
          skills_display: 'Athletics, Defense, Jiujutsu, "Lore: Theology/Pick One", Meditation, and Any 2 skills'
          skill_choice: 'Any 2 skills and Any Emphasis for "Lore: Theology"'
          shugenja: false
          honor: 4.5
          starting_technique: Destiny's Hand
          pg: Core pg. 232
