---
l5r:
  schools:
        -
          name: Hida Bushi
          clan: Crab
          trait_bonus: Stamina
          skills: [Athletics, Defense, Heavy Weapons/Tetsubo, Intimidation, Kenjutsu, "Lore: Shadowlands"]
          skills_display: "Athletics, Defense, Heavy Weapons/Tetsubo, Intimidation, Kenjutsu, Lore: Shadowlands, and Any Bugei skill"
          skill_choice: "Any Bugei skill"
          shugenja: false
          honor: 3.5
          starting_technique: The Way of the Crab
          techniques: ['"The Way of the Crab"', '"The Mountain Does Not Move"', '"Two Pincers, One Mind"', '"Devastating Blow"', '"The Mountain Does Not Fall"']
        -
          name: Kuni Shugenja
          clan: Crab
          trait_bonus: Willpower
          skills: [Calligraphy/Cipher, Defense, "Lore: Shadowlands", "Lore: Shadowlands", "Lore: Theology", Spellcraft]
          skills_display: "Calligraphy/Cipher, Defense, Lore: Shadowlands, Lore: Theology, Spellcraft, and Any Weapon skill"
          skill_choice: "Any Weapon skill"
          shugenja: true
          affinity: Earth
          deficiency: Air
          spells: Universal, 3 Earth, 3 Fire, and 1 Water
          spell_choice: "3 Earth, 2 Fire, 1 Water"
          honor: 2.5
          starting_technique: Gaze into Shadow
        -
          name: Yasuki Courtier
          clan: Crab
          trait_bonus: Perception
          skills: [Commerce/Appraisal, Courtier, Defense, Etiquette, Intimidation, Sincerity/Deceit]
          skills_display: "Commerce/Appraisal, Courtier, Defense, Etiquette, Intimidation, Sincerity/Deceit, and Any Merchant skill"
          skill_choice: "Any Merchant skill"
          shugenja: false
          honor: 2.5
          starting_technique: The Way of the Carp
          techniques: ['"The Way of the Carp"', '"Do As We Say"', '"Treasures of the Carp"', '"Wiles of the Carp"', '"What is Yours is Mine"']
        -
          name: Hiruma Bushi
          clan: Crab
          trait_bonus: Willpower
          skills: [Athletics, Hunting, Kenjutsu/Katana, Kyujutsu, "Lore: Shadowlands", Stealth]
          skills_display: "Athletics, Hunting, Kenjutsu/Katana, Kyujutsu, Lore: Shadowlands, Stealth, and Any skill"
          skill_choice: "Any skill"
          shugenja: false
          honor: 4.5
          starting_technique: "Torch's Flame Flickers"
          techniques: ["'Torch's Flame Flickers'", "'Wolf's Little Lesson'", '"Hummingbird Wings"', '"Shark Smells Blood"', '"Daylight Wastes No Movement"']
        -
          name: Kakita Bushi
          clan: Crane
          trait_bonus: Reflexes
          skills: [Etiquette, Iaijutsu/Focus, Kenjutsu, Kyujutsu, Sincerity, Tea Ceremony]
          skills_display: "Etiquette, Iaijutsu/Focus, Kenjutsu, Kyujutsu, Sincerity, Tea Ceremony, and Any Bugei or High skill"
          skill_choice: "Any Bugei or High skill"
          shugenja: false
          honor: 6.5
          starting_technique: The Way of the Crane
          techniques: ['"The Way of the Crane"', '"Speed of Lightning"', '"First and Last Strike"', '"One Strike, Two Cuts"', '"Strike With No Thoughts"']
        -
          name: Disciples of Sun Tao
          clan: None
          trait_bonus: Reflexes
          skills: [Athletics, Defense, Hunting, Iaijutsu, Kenjutsu]
          skills_display: "Athletics, Defense, Hunting, Iaijutsu, Kenjutsu, Any 2 skills"
          skill_choice: "Any 2 skills"
          shugenja: false
          honor: 4.5
          starting_technique: The Gaze of Sun Tao
        -
          name: Self-Taught Shugenja
          clan: None
          trait_bonus: Willpower
          skills: [Athletics, Hunting, Meditation, Spellcraft]
          skills_display: "Athletics, Hunting, Meditation, Spellcraft, and Any 3 non-High skills"
          skill_choice: "Any 3 non-High skills"
          shugenja: true
          affinity: Any non-Void
          deficiency: Opposing Element and 1 Choice
          aff_def_choice: true
          spells: Universal and any five you can cast. None can be for an element you have a deficiency in.
          spell_choice: Any 5 non-Deficiency
          honor: 4.0
          starting_technique: "The Kami's Gift"
        -
          name: Dutiful Disciple Shugenja
          clan: None
          trait_bonus: Intelligence
          skills: [Calligraphy, "Lore: Theology", Meditation, Spellcraft]
          skills_display: 'Calligraphy, "Lore: Theology", Meditation, Spellcraft, Any 2 skills, and Any Lore skill'
          skill_choice: "Any 2 skills and Any Lore skill"
          shugenja: true
          affinity: "Any non-Void"
          deficiency: "Opposing Element"
          aff_def_choice: true
          spells: Universal, 3 Affinity, 2 non-Deficiency, and 1 different non-Deficiency.
          spell_choice: 3 Affinity, 2 non-Deficiency, 1 different non-Deficiency
          honor: 4.0
          starting_technique: Soul of Study
        -
          name: Ronin Order Shugenja
          clan: None
          trait_bonus: Awareness
          skills: [Calligraphy/Cipher, Divination, "Lore: Theology", Meditation, Spellcraft]
          skills_display: 'Calligraphy/Cipher, Divination, "Lore: Theology", Meditation, Spellcraft, Any skill, and Any Lore skill'
          skill_choice: "Any skill and Any Lore skill"
          shugenja: true
          affinity: "Air"
          deficiency: "Earth"
          spells: Universal, 3 Air, 2 Water, and 1 Fire
          spell_choice: 3 Air, 2 Water, 1 Fire
          honor: 5.0
          starting_technique: The Path of Discipline
        -
          name: Four Temples
          clan: Monk
          trait_bonus: Awareness
          skills: [Courtier, Etiquette, Jiujutsu, "Lore: Theology/Shintao", Meditation]
          skills_display: 'Courter, Etiquette, Jiujutsu, "Lore: Theology/Shintao", Meditation, Any 2 skills'
          skill_choice: "Any 2 skills"
          shugenja: false
          honor: 6.5
          starting_technique: Soul of Civility
        -
          name: The Order of Heroes
          clan: Monk
          trait_bonus: Perception
          skills: [Athletics, Defense, Jiujutsu, "Lore: Theology", Meditation]
          skills_display: 'Athletics, Defense, Jiujutsu, "Lore: Theology/Pick One", Meditation, and Any 2 skills'
          skill_choice: 'Any 2 skills and Any Emphasis for "Lore: Theology"'
          shugenja: false
          honor: 4.5
          starting_technique: Destiny's Hand
