---
plugins:
  disabled_plugins:
  - achievements
  - fs3combat
  - fs3skills
  - achievements
  optional_plugins:
  - achievements
  - chargen
  - cookies
  - events
  - fs3combat
  - fs3skills
  - ranks
  - weather
  - achievements
